base: "%env(SITE_FCBIGFOOT_BASE)%"
dependencies:
  - typo3-incubator/theme-fcbigfoot
  - typo3-incubator/surfcamp-events
languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: "FC Bigfoot"
routeEnhancers:
  EventPlugin:
    type: Extbase
    extension: SurfcampEvents
    plugin: EventList
    routes:
      - routePath: "/event/{event}"
        _controller: "Event::detail"
        _arguments:
          event: event
    defaultController: "Event::list"
  EventMapPlugin:
    type: Extbase
    extension: SurfcampEvents
    plugin: EventLocationsMap
    routes:
      - routePath: "/event/{event}"
        _controller: "Event::detail"
        _arguments:
          event: event
    defaultController: "Event::locationsMap"
